package model;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Represents an image uploaded by the user. Each image has an ID, uploader, file path, upload
 * timestamp and an optional description.
 */
public class Image {

  private final String id;
  private final String uploader;
  private final String filePath;
  private final LocalDateTime timestamp;
  private final String description;

  /**
   * Constructs an Image object with all fields initialized.
   *
   * @param uploader    the user who uploaded the image
   * @param filePath    the path of the image file
   * @param description optional text description of this image; empty string by default
   */
  public Image(String uploader, String filePath, String description) {
    this.id = UUID.randomUUID().toString();
    this.uploader = uploader;
    this.filePath = filePath;
    this.timestamp = LocalDateTime.now();
    this.description = description == null ? "" : description;
  }


  /**
   * Returns the unique identifier generated by the system for this image.
   */
  public String getId() {
    return id;
  }

  /**
   * Returns the uploader of this image.
   */
  public String getUploader() {
    return uploader;
  }

  /**
   * Returns the full file path of this image.
   */
  public String getFilePath() {
    return filePath;
  }

  /**
   * Returns the timestamp when this image was uploaded.
   */
  public LocalDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * Returns the description of this image.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Returns a string representation of this image.
   *
   * @return Image[id, uploader, filePath, timestamp]
   */
  @Override
  public String toString() {
    return String.format("Image[id=%s, uploader=%s, filePath=%s, timestamp=%s]",
        id, uploader, filePath, timestamp);
  }

  /**
   * Compares this image to another image for equality. Two images are considered equal if they have
   * the same ID.
   *
   * @param o the object to be compared
   * @return true if two images are equal, false otherwise
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image other = (Image) o;
    return id.equals(other.id);
  }

  /**
   * Returns the hash code of this image. The hash code is based on the image ID, consistent with
   * equals().
   *
   * @return the hash code based on the image ID
   */
  @Override
  public int hashCode() {
    return Objects.hash(id);
  }
}
